# Import Libraries

In [1]:
# import libraries
import numpy as np
import pandas as pd

# Data Preprocessing

In [2]:
# Read book dataset and assign it to the variable b
b = pd.read_csv('books.csv')
print(b.shape)
b.head()

(2312, 5)

   book_id  avg_rating  no_of_ratings  user_id  user_rating
0     4833        4.25         7156.0     3466            0
1      590        4.31         7821.0     3466            5
2     4264        4.08         3836.0     3453            5
3     3361        3.52         1245.0     3453            4
4     4535        4.13         3107.0     3453            0

In [3]:
# There is no need for the columns "no_of_ratings" and "avg_rating"
# in our implementation therefore we drop these columns
# we assigned remain data to the variable ratings
ratings = b.drop(['no_of_ratings', 'avg_rating'], axis=1)

In [4]:
# Print first 5 rows from ratings dataset
ratings.head()

   book_id  user_id  user_rating
0     4833     3466            0
1      590     3466            5
2     4264     3453            5
3     3361     3453            4
4     4535     3453            0

In [5]:
# Print shape of ratings dataset
ratings.shape

(2312, 3)

In [6]:
# If there is no NaN value in any row then remove that row
ratings.dropna(inplace=True)

In [7]:
# Print shape of ratings dataset
ratings.shape

(2312, 3)

In [8]:
# We group rows by user_id column and remove the groups which has only one element
# We split using scikit-leanr's train_test_split function and set stratify property 
# of that function to user_id, therefore it isn't possible to split rows that belongs
# to exactly one user
ratings = ratings.groupby(['user_id']).filter(lambda x: len(x) > 1)

In [9]:
# Prints number of unique books from ratings dataset 
len(ratings.book_id.unique())

710

In [10]:
# Prints number of unique users from ratings dataset 
len(ratings.user_id.unique())

84

In [11]:
# Check how many Null value he have in ratings dataset
ratings.isnull().sum()

book_id        0
user_id        0
user_rating    0
dtype: int64

In [12]:
# Print shape of ratings dataset
ratings.shape

(2206, 3)

In [13]:
# Drop duplicate rows from the dataset ratings
ratings.drop_duplicates(subset=['book_id', 'user_rating', 'user_id'], inplace=True)

In [14]:
# Print shape of ratings dataset
ratings.shape

(2189, 3)

In [15]:
# Reset index for the dataset ratings
ratings.reset_index(inplace=True)

In [16]:
# Print first five rows from the dataset ratings
ratings.head()

   index  book_id  user_id  user_rating
0      0     4833     3466            0
1      1      590     3466            5
2      2     4264     3453            5
3      3     3361     3453            4
4      4     4535     3453            0

In [17]:
# Print shape of ratings dataset
ratings.shape

(2189, 4)

# User Based Collaorative Filtering

In [18]:
#Import the train_test_split function
from sklearn.model_selection import train_test_split

In [19]:
#Assign X as the original ratings dataframe and y as the user_id column of ratings.
X = ratings.copy()
y = ratings['user_id']

In [20]:
#Split into training and test datasets, stratified along user_id
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, stratify=y, random_state=42)

In [21]:
#Import the mean_squared_error function
from sklearn.metrics import mean_squared_error

#Function that computes the root mean squared error (or RMSE)
def rmse(y_true, y_pred):
  return np.sqrt(mean_squared_error(y_true, y_pred))

In [22]:
#Function to compute the RMSE score obtained on the testing set by a model
def score(cf_model):
  #Construct a list of user-movie tuples from the testing dataset
  id_pairs = zip(X_test['user_id'], X_test['book_id'])
  #Predict the rating for every user-movie tuple
  y_pred = np.array([cf_model(user, book) for (user, book) in id_pairs])
  #Extract the actual ratings given by the users in the test data
  y_true = np.array(X_test['user_rating'])
  #Return the final RMSE score
  return rmse(y_true, y_pred)

In [23]:
#Build the ratings matrix using pivot_table function
r_matrix = X_train.pivot_table(values='user_rating', index='user_id', columns='book_id')

r_matrix.sample(20)

book_id  6     7     9     15    21    29    ...  4968  4971  4975  4978  4991  4995
user_id                                      ...
2283      NaN   NaN   NaN   NaN   NaN   NaN  ...   NaN   NaN   NaN   NaN   NaN   NaN
7130      NaN   NaN   NaN   NaN   NaN   NaN  ...   NaN   NaN   NaN   NaN   NaN   NaN
3229      NaN   NaN   NaN   NaN   NaN   NaN  ...   NaN   NaN   NaN   NaN   NaN   NaN
3262      NaN   NaN   NaN   NaN   NaN   NaN  ...   NaN   NaN   NaN   NaN   NaN   NaN
3480      NaN   NaN   NaN   NaN   NaN   NaN  ...   NaN   NaN   NaN   NaN   NaN   NaN
117       NaN   NaN   NaN   NaN   NaN   NaN  ...   NaN   NaN   NaN   NaN   NaN   NaN
3115      NaN   NaN   NaN   NaN   NaN   NaN  ...   NaN   NaN   NaN   NaN   NaN   NaN
3364      NaN   NaN   NaN   NaN   NaN   NaN  ...   NaN   NaN   NaN   NaN   NaN   NaN
2672      NaN   NaN   NaN   NaN   NaN   NaN  ...   NaN   NaN   NaN   NaN   NaN   NaN
330       NaN   NaN   NaN   NaN   NaN   NaN  ...   NaN   NaN   NaN   NaN   NaN   NaN
1183      NaN   NaN   NaN   NaN   NaN   NaN  ...   NaN   NaN   NaN   NaN   NaN   NaN
1784      NaN   NaN   NaN   NaN   NaN   NaN  ...   NaN   NaN   NaN   NaN   NaN   NaN
3393      NaN   NaN   NaN   NaN   NaN   NaN  ...   NaN   NaN   NaN   NaN   NaN   NaN
703       NaN   NaN   NaN   NaN   NaN   NaN  ...   5.0   NaN   NaN   2.0   NaN   NaN
3461      NaN   NaN   NaN   NaN   NaN   NaN  ...   NaN   NaN   NaN   NaN   NaN   NaN
2474      NaN   NaN   NaN   NaN   NaN   NaN  ...   NaN   NaN   NaN   NaN   NaN   NaN
3468      NaN   NaN   NaN   NaN   NaN   NaN  ...   NaN   NaN   NaN   NaN   NaN   NaN
3331      NaN   NaN   NaN   NaN   NaN   NaN  ...   NaN   NaN   NaN   NaN   NaN   NaN
2760      NaN   NaN   NaN   NaN   NaN   NaN  ...   NaN   NaN   NaN   NaN   NaN   NaN
176       NaN   NaN   NaN   NaN   NaN   NaN  ...   NaN   NaN   NaN   NaN   NaN   NaN

[20 rows x 677 columns]

In [24]:
# Print shape of ratings matrix
r_matrix.shape

(84, 677)

In [25]:
#Create a dummy ratings matrix with all null values imputed to 0
r_matrix_dummy = r_matrix.copy().fillna(0)

In [26]:
# Import cosine_score
from sklearn.metrics.pairwise import cosine_similarity

In [27]:
#Compute the cosine similarity matrix using the dummy ratings matrix
cosine_sim = cosine_similarity(r_matrix_dummy, r_matrix_dummy)

In [28]:
#Convert into pandas dataframe
cosine_sim = pd.DataFrame(cosine_sim, index=r_matrix.index, columns=r_matrix.index)

In [29]:
cosine_sim.head(10)

user_id      117       176   232       295   ...  3486  3497  7130      7131
user_id                                      ...
117      1.000000  0.000000   0.0  0.025962  ...   0.0   0.0   0.0  0.000000
176      0.000000  1.000000   0.0  0.181356  ...   0.0   0.0   0.0  0.000000
232      0.000000  0.000000   1.0  0.000000  ...   0.0   0.0   0.0  0.000000
295      0.025962  0.181356   0.0  1.000000  ...   0.0   0.0   0.0  0.000000
330      0.000000  0.000000   0.0  0.000000  ...   0.0   0.0   0.0  0.000000
397      0.000000  0.000000   0.0  0.000000  ...   0.0   0.0   0.0  0.000000
484      0.000000  0.000000   0.0  0.000000  ...   0.0   0.0   0.0  0.100125
703      0.084509  0.209076   0.0  0.000000  ...   0.0   0.0   0.0  0.000000
853      0.000000  0.089245   0.0  0.000000  ...   0.0   0.0   0.0  0.000000
1083     0.000000  0.000000   0.0  0.000000  ...   0.0   0.0   0.0  0.000000

[10 rows x 84 columns]

In [30]:
#User Based Collaborative Filter using Weighted Mean Ratings
def cf_user_wmean(user_id, book_id):
  #Check if movie_id exists in r_matrix
  if book_id in r_matrix:
    #Get the similarity scores for the user in question with every other user
    sim_scores = cosine_sim[user_id]
    #Get the user ratings for the movie in question
    m_ratings = r_matrix[book_id]

    #Extract the indices containing NaN in the m_ratings series
    idx = m_ratings[m_ratings.isnull()].index
    #Drop the NaN values from the m_ratings Series
    m_ratings = m_ratings.dropna()
    m_ratings.reset_index()
    #Drop the corresponding cosine scores from the sim_scores series
    sim_scores = sim_scores.drop(idx)

    #Compute the final weighted mean
    wmean_rating = np.dot(sim_scores, m_ratings)/ (sim_scores.sum()  + 0.00000001)
  else:
    #Default to a rating of 3.0 in the absence of any information
    wmean_rating = 3.0
  return wmean_rating

In [31]:
score(cf_user_wmean)

2.001154409808239

# Testing

In [32]:
# user based
b_id = 862
u_id = 3461

In [33]:
ratings[(ratings['book_id'] == b_id) & (ratings['user_id'] == u_id)]

     index  book_id  user_id  user_rating
176    176      862     3461            3

In [34]:
# Predicts ratings for the user id equal to 3461 and book id equal to 862
cf_user_wmean(u_id, b_id)

2.94207940734678

In [48]:
# Get all 5 rated books
tmp5 = X_test[X_test["user_rating"]==5]
tmp5

      index  book_id  user_id  user_rating
1953   1970     3900     3482            5
1278   1285     4240     3471            5
544     548     1180     3476            5
1281   1288     3857     3471            5
283     283     2276     3470            5
...     ...      ...      ...          ...
473     477     1773     3217            5
1343   1350     4354     3470            5
1955   1972        6     3484            5
1159   1164     3757     3426            5
721     725      875     3453            5

[104 rows x 4 columns]

In [49]:
# Calculate the mean of predicted values for this models based on ratings rated 
# by users as 5
list = [] 
def avg_rating(cf_model):   
  id_pairs = zip(tmp5['user_id'], tmp5['book_id'])
  y_pred = np.array([cf_model(user, book) for (user, book) in id_pairs])   
  lst = list.append(y_pred)   
  return np.mean(list)

avg_rating(cf_user_wmean)

2.7150544847285945